### ISSUE TITLE
建議可以改用ListenerAdapter

### ISSUE THREAD

**Issue by Kayxue** [Gary50613/Jena#2]
建議可以改用ListenerAdapter
![20210509_115354_rmscr](https://user-images.githubusercontent.com/26020165/117560086-4487f380-b0bd-11eb-814b-07906001e8a4.jpg)

**Comment by xiaoxigua-1** [comment]
好電
凱恩都那麼電嗎？

**Comment by xiaoxigua-1** [comment]
> 建議可以改用ListenerAdapter
> 
> ![20210509_115354_rmscr](https://user-images.githubusercontent.com/26020165/117560086-4487f380-b0bd-11eb-814b-07906001e8a4.jpg)
> 
> 

這也太電了吧

**Comment by kane50613** [comment]
fixed~
